### PR TITLE
chore: update dependencies + capacitor 5

### PR DESCRIPTION
**Pull request by Dwimcore**

### CODE REVIEW

**Comment by Dwimcore** [comment]
Temporarily integrated community/http code to allow downloading files, will remove when integrated by ionic team in @capacitor/filesystem

**Comment by afilp** [comment]
Hi @Dwimcore, We are very interested in your solution (we could not make it work though). Do you want us to help with some testing? Please let us know what to do and we will help. Thanks a lot!

**Comment by Dwimcore** [comment]
Hello @afilp, sorry for the response time, I'm not 100% on the project on which we're using this plugin. How did it not work for you ? (error messages, bugs ?)

We're using this version on a app in production and it seems to work quite good :)

**Comment by afilp** [comment]
@Dwimcore When you say "this version", you mean the one with this PR of yours merged? I would like to know which version to use for the plugin to work as expected. Thanks a lot!

**Comment by Dwimcore** [comment]
@afilp It depends on your capacitor core version, but the code in this PR (that will not be merged until ionic team implements file download into plugin @capacitor/filesystem) is working on latest capacitor version :)

**Comment by emelampianakis** [comment]
Hi @Dwimcore this plugin is working fine so far but there is a need for our project to migrate to capacitor 5. Is this plugin going to be upgraded to support capacitor 5? Is there something we can help with? Thanks in advance!

**Comment by Dwimcore** [comment]
Hi @emelampianakis, it should be working with capacitor 5 now :)

**Pull request merged**
